[package]
name = "shery"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
anyhow = "1.0.95"
clap = { version = "4.5.30", features = ["derive"] }
serde = {version="1.0.217", features=["derive"]}
serde_json = "1.0.139"
